### ISSUE TITLE
MySQL error: (2014) Commands out of sync

### ISSUE THREAD

**Issue by ownmaster** [StudiOwens/email-mysql-csv#3]
Hi,

When I tried to create an email with multiple attachments by calling a stored procedure in each query, I was getting an error:

> ERROR: Invalid query
> MySQL error: (2014)Commands out of sync; you can't run this command now

Fixed that by adding `$mysqli->next_result()` before the end of `buildCSV`.

**Comment by StudiOwens** [comment]
That is correct. If you add a stored procedure to the query it's going to run multiple queries and you will need the next result.

Thank for reporting this for others that might run into this down the road.

**Comment by ownmaster** [comment]
@StudiOwens Do you plan to update `buildCSV()` code?

**Comment by StudiOwens** [comment]
I have no plans on implementing suppport for stored procedures into this class.

Feel free to fork the code.

For anyone else looking into using stored procedures. If the stored procedures return result sets, then the first result set is fetched into a buffered result set, and the additional stored procedure result sets are hidden from the user. This will cause the mysqli_query() to fail. The result sets returned from a stored procedure can be fetched using mysqli_real_query() or mysqli_multi_query(). Then to retrieve the resultset from the first query you can use mysqli_use_result() or mysqli_store_result(). All subsequent query results can be processed using mysqli_more_results() and mysqli_next_result().

http://php.net/manual/en/mysqli.quickstart.stored-procedures.php

**Comment by ownmaster** [comment]
@StudiOwens Thanks for the hint, I'll try to make and publish a "universal" enhancement.
