### ISSUE TITLE
Zipping the CSV file

### ISSUE THREAD

**Issue by spaceknight** [StudiOwens/email-mysql-csv#4]
Hello, your site studioowens seems to be closed at the moment, so I submit my issue here.

First of all, thanks for this class, really. It is exactly what I was looking for. It allows me to get a CSV of any query I want, unlike dumping a whole table or database.

Second, as a CSV is a text file, I would like to save space and bandwidth by zipping it before sending. Any ideas on how I can do that? PHP has builtin zip support, so maybe...

Have a nice day,

**Comment by StudiOwens** [comment]
I'm way overworked at the moment and don't have time to write a solution. This should point you in a direction.

You will probably want to look at ZipArchive and possibly ZipArchive()::addFromString to create your zip and save it to storage.

https://www.php.net/ZipArchive
https://www.php.net/manual/en/ziparchive.addfromstring.php

Then you will want to get the zip file from storage and attach it to the email. Maybe something like.
chunk_split(base64_encode(file_get_contents()));

https://www.php.net/manual/en/function.file-get-contents.php
https://www.php.net/manual/en/function.base64-encode.php
https://www.php.net/manual/en/function.chunk-split.php

You could clean up your own zip debris by going back to delete the zip from storage when finished.
unlink( )

https://www.php.net/manual/en/function.unlink.php
